export const userList = [
    { value: 'XFish', label: 'XFish'},
    { value: 'SteakFou2', label: 'SteakFou2' },
    { value: 'BoyLoto', label: 'BoyLoto'},
    { value: 'Daniel43', label: 'Daniel43'},
    { value: 'LOliLOL', label: 'LOliLOL'},
    { value: 'jj32', label: 'jj32'},
    { value: 'SynnLive', label: 'SynnLive'},
    { value: 'Din_4o', label: 'Din_4o'},
    { value: 'patoch91', label: 'patoch91'},
    { value: 'jOsEpH', label: 'jOsEpH'},
    { value: 'nono12', label: 'nono12'},
    { value: 'mirtille_du_love', label: 'mirtille_du_love'},
    { value: 'Rirou1999', label: 'Rirou1999'},
    { value: 'pepedu36', label: 'pepedu36'},
    { value: 'berNARAS', label: 'berNARAS'},
    { value: 'CoccinelL', label: 'CoccinelL'},
    { value: 'Popeye20', label: 'Popeye20'},
    { value: 'JulieJolie', label: 'JulieJolie'},
    { value: 'Naniiii', label: 'Naniiii'},
    { value: 'ouiLOL', label: 'jOsEpH'},
    { value: 'lotoOxygene', label: 'lotoOxygene'},
    { value: 'solELE', label: 'solELE'},
    { value: '1256y7', label: '1256y7'},
    { value: 'out_fire3', label: 'out_fire3'},
    { value: 'M1R1NT', label: 'M1R1NT'},
    { value: 'vlasoooF', label: 'vlasoooF'},
    { value: 'oRouuuuu', label: 'oRouuuuuu'},
    { value: 'funnyLOTO', label: 'funnyLOTO'}

];